export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
// ASSET
export const RECEIVE_ASSETLIST = 'RECEIVE_ASSETLIST'
export const RECEIVE_ASSETLOCATION = 'RECEIVE_ASSETLOCATION'
export const RECEIVE_DEPARMENTTLIST = 'RECEIVE_DEPARMENTTLIST'
export const RECEIVE_PERSONTLIST = 'RECEIVE_PERSONTLIST'
export const RECEIVE_CHECKLIST = 'RECEIVE_CHECKLIST'
